name: Build to dist branch
on:
  push:
    branches:
      - main

jobs:
  do-push:
    name: Quasar build to dist branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.14.0

      - name: npm install
        run: npm install -g @quasar/cli && npm install

      - name: quasar build
        run: quasar build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: dist/spa
          GITHUB_TOKEN: ${{ secrets.PERSON_ACCESS_TOKEN }}
