name: Build development image

on:
  push:
    branches-ignore:
      - "dependabot/**"
    tags:
      - v*

jobs:
  build-and-push:
    name: Publish docker images to Docker Hub
    runs-on: ubuntu-18.04

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU for cross platform builds
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Convert to a valid docker tagname
      # refs/tags/v1.2.3 => v1.2.3
      # refs/heads/unstable => unstable
      # refs/heads/feature/foo => foo
      # refs/pull/421/merge => merge
      - name: Get branch or tag name
        id: source_name
        run: echo ::set-output name=SOURCE_NAME::${GITHUB_REF##*/}

      - name: Build and push
        if: contains(fromJson('["refs/heads/unstable", "refs/heads/stable"]'), github.ref)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            muveex/kikoeru-quasar:${{ steps.source_name.outputs.SOURCE_NAME }}
            muveex/kikoeru-quasar:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Temp fix according to official document at
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
      # They are working to refactor with GitHub cache backend
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
